### ISSUE TITLE
No support for redis authentication

### ISSUE THREAD

**Issue by orangepeelbeef** [richardhenry/hotqueue#14]
There is no support for connecting to redis that requires authentication
(at least not documented)

>>> from hotqueue import HotQueue
>>> queue = HotQueue("myqueue", host="localhost", port=6379, db=0)
>>> queue.put(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/hotqueue.py", line 120, in put
    self.__redis.rpush(self.key, *msgs)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 1265, in rpush
    return self.execute_command('RPUSH', name, *values)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 565, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 577, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 574, in read_response
    raise response
redis.exceptions.ResponseError: NOAUTH Authentication required.

**Comment by orangepeelbeef** [comment]
queue = HotQueue("myqueue", host="localhost", port=6379, db=0, password="mypassword")
