### ISSUE TITLE
Error when installing: TypeError: chown() missing 1 required positional argument: 'numeric_owner'

### ISSUE THREAD

**Issue by zhangqunshi** [richardhenry/hotqueue#17]
Hi guys,

When I install this lib, i got the following error on windows 7:

```
$ pip install -U hotqueue
Collecting hotqueue
  Using cached hotqueue-0.2.7.tar.gz
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.14.tar.gz
    Extracting in C:\Users\user1\AppData\Local\Temp\tmpts_g6vwx
    Traceback (most recent call last):
      File "c:\users\user1\appdata\local\temp\pip-build-7dkaissd\hotqueue\distribute_setup.py", line 143, in use_setuptools
        raise ImportError
    ImportError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user1\AppData\Local\Temp\pip-build-7dkaissd\hotqueue\setup.py", line 7, in <module>
        from distribute_setup import use_setuptools; use_setuptools()
      File "c:\users\user1\appdata\local\temp\pip-build-7dkaissd\hotqueue\distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "c:\users\user1\appdata\local\temp\pip-build-7dkaissd\hotqueue\distribute_setup.py", line 125, in _do_download
        _build_egg(egg, tarball, to_dir)
      File "c:\users\user1\appdata\local\temp\pip-build-7dkaissd\hotqueue\distribute_setup.py", line 99, in _build_egg
        _extractall(tar)
      File "c:\users\user1\appdata\local\temp\pip-build-7dkaissd\hotqueue\distribute_setup.py", line 467, in _extractall
        self.chown(tarinfo, dirpath)
    TypeError: chown() missing 1 required positional argument: 'numeric_owner'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\user1\AppData\Local\Temp\pip-build-7dkaissd\hotqueue\
```

Anybody can help me?

Thanks,
Kris

**Comment by richardhenry** [comment]
This might be an issue with distribute on Windows, I'm not sure. I actually just merged in a pull request that might help with this, so try installing the latest version from GitHub:

    pip install git+git://github.com/richardhenry/hotqueue

Let me know if this works.

**Comment by zhangqunshi** [comment]
it's work, thanks richardhenry.

**Comment by richardhenry** [comment]
Awesome
